services:
  postgres:
    image: postgres:17.4
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@platzi.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
